#CREATE TABLE @cdmDatabaseSchema.observation (
#            observation_id integer NOT NULL,
#            person_id integer NOT NULL,
#            observation_concept_id integer NOT NULL,
#            observation_date date NOT NULL,
#            observation_datetime TIMESTAMP NULL,
#            observation_type_concept_id integer NOT NULL,
#            value_as_number NUMERIC NULL,
#            value_as_string varchar(60) NULL,
#            value_as_concept_id Integer NULL,
#            qualifier_concept_id integer NULL,
#            unit_concept_id integer NULL,
#            provider_id integer NULL,
#            visit_occurrence_id integer NULL,
#            visit_detail_id integer NULL,
#            observation_source_value varchar(50) NULL,
#            observation_source_concept_id integer NULL,
#            unit_source_value varchar(50) NULL, 
#            qualifier_source_value varchar(50) NULL );
#
